# Generated by Django 5.1.2 on 2024-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
        ),
    ]
